######################################################################
# Automatically generated by qmake (2.01a) Sa 28. Jan 13:12:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Bild.h Programm.h
SOURCES += Bild.cpp main.cpp Programm.cpp
